begin;

create table if not exists public.moderation_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  target_type text not null check (target_type in ('chat','pixel')),
  reason text not null check (reason in ('bullying','inappropriate','personal_data','spam','cheating','other')),
  details text check (details is null or char_length(details)<=500),
  chat_message_id bigint,
  season_id bigint,
  pixel_x integer,
  pixel_y integer,
  target_user_id uuid references public.profiles(id) on delete set null,
  content_snapshot text,
  pixel_color text,
  target_class_name text,
  status text not null default 'open' check (status in ('open','resolved','dismissed')),
  admin_note text check (admin_note is null or char_length(admin_note)<=500),
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  check ((target_type='chat' and chat_message_id is not null) or
         (target_type='pixel' and season_id is not null and pixel_x is not null and pixel_y is not null))
);

create index if not exists moderation_reports_status_created_idx on public.moderation_reports(status,created_at desc);
create unique index if not exists moderation_reports_open_chat_unique on public.moderation_reports(reporter_id,chat_message_id) where status='open' and target_type='chat';
create unique index if not exists moderation_reports_open_pixel_unique on public.moderation_reports(reporter_id,season_id,pixel_x,pixel_y) where status='open' and target_type='pixel';

alter table public.moderation_reports enable row level security;
revoke all on table public.moderation_reports from public,anon,authenticated;
revoke all on sequence public.moderation_reports_id_seq from public,anon,authenticated;

create or replace function public.create_chat_report(p_message_id bigint,p_reason text,p_details text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid(); v_message record;
begin
  if v_uid is null or not exists(select 1 from public.profiles where id=v_uid and coalesce(banned,false)=false) then
    return jsonb_build_object('success',false,'error','ACTIVE_USER_REQUIRED');
  end if;
  if p_reason not in ('bullying','inappropriate','personal_data','spam','cheating','other') or char_length(coalesce(p_details,''))>500 then
    return jsonb_build_object('success',false,'error','INVALID_REPORT');
  end if;
  if (select count(*) from public.moderation_reports where reporter_id=v_uid and created_at>now()-interval '24 hours')>=5 then
    return jsonb_build_object('success',false,'error','REPORT_LIMIT');
  end if;
  select cm.id,cm.user_id,cm.message,cm.message_type into v_message from public.chat_messages cm where cm.id=p_message_id;
  if v_message.id is null or v_message.message_type='system' then return jsonb_build_object('success',false,'error','TARGET_NOT_FOUND'); end if;
  if v_message.user_id=v_uid then return jsonb_build_object('success',false,'error','OWN_CONTENT'); end if;
  insert into public.moderation_reports(reporter_id,target_type,reason,details,chat_message_id,target_user_id,content_snapshot)
  values(v_uid,'chat',p_reason,nullif(btrim(coalesce(p_details,'')),''),v_message.id,v_message.user_id,v_message.message);
  return jsonb_build_object('success',true);
exception when unique_violation then return jsonb_build_object('success',false,'error','DUPLICATE_REPORT');
end $$;

create or replace function public.create_pixel_report(p_season_id bigint,p_x integer,p_y integer,p_reason text,p_details text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_uid uuid:=auth.uid(); v_pixel record;
begin
  if v_uid is null or not exists(select 1 from public.profiles where id=v_uid and coalesce(banned,false)=false) then
    return jsonb_build_object('success',false,'error','ACTIVE_USER_REQUIRED');
  end if;
  if p_x<0 or p_x>=300 or p_y<0 or p_y>=424 or p_reason not in ('bullying','inappropriate','personal_data','spam','cheating','other') or char_length(coalesce(p_details,''))>500 then
    return jsonb_build_object('success',false,'error','INVALID_REPORT');
  end if;
  if (select count(*) from public.moderation_reports where reporter_id=v_uid and created_at>now()-interval '24 hours')>=5 then
    return jsonb_build_object('success',false,'error','REPORT_LIMIT');
  end if;
  select px.user_id,px.color,c.name as class_name into v_pixel
  from public.pixels px left join public.classes c on c.id=px.class_id
  where px.season_id=p_season_id and px.x=p_x and px.y=p_y;
  if v_pixel.user_id is null then return jsonb_build_object('success',false,'error','TARGET_NOT_FOUND'); end if;
  if v_pixel.user_id=v_uid then return jsonb_build_object('success',false,'error','OWN_CONTENT'); end if;
  insert into public.moderation_reports(reporter_id,target_type,reason,details,season_id,pixel_x,pixel_y,target_user_id,pixel_color,target_class_name,content_snapshot)
  values(v_uid,'pixel',p_reason,nullif(btrim(coalesce(p_details,'')),''),p_season_id,p_x,p_y,v_pixel.user_id,v_pixel.color,v_pixel.class_name,
    format('X %s, Y %s, цвет %s, класс %s',p_x,p_y,v_pixel.color,coalesce(v_pixel.class_name,'—')));
  return jsonb_build_object('success',true);
exception when unique_violation then return jsonb_build_object('success',false,'error','DUPLICATE_REPORT');
end $$;

create or replace function public.admin_get_moderation_reports(p_status text default 'open')
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare v_result jsonb;
begin
  if auth.uid() is null or not exists(select 1 from public.profiles where id=auth.uid() and role='admin' and coalesce(banned,false)=false) then raise exception 'ADMIN_REQUIRED'; end if;
  if p_status not in ('open','resolved','dismissed','all') then raise exception 'INVALID_STATUS'; end if;
  select jsonb_build_object('reports',coalesce(jsonb_agg(jsonb_build_object(
    'report_id',mr.id,'target_type',mr.target_type,'reason',mr.reason,'details',mr.details,'status',mr.status,
    'created_at',mr.created_at,'content_snapshot',mr.content_snapshot,'pixel_x',mr.pixel_x,'pixel_y',mr.pixel_y,
    'pixel_color',mr.pixel_color,'target_class_name',mr.target_class_name,'admin_note',mr.admin_note,
    'reporter_username',reporter.username,'reporter_nickname',reporter.nickname,
    'target_username',target.username,'target_nickname',target.nickname) order by mr.created_at desc),'[]'::jsonb))
  into v_result from public.moderation_reports mr
  join public.profiles reporter on reporter.id=mr.reporter_id
  left join public.profiles target on target.id=mr.target_user_id
  where p_status='all' or mr.status=p_status;
  return v_result;
end $$;

create or replace function public.admin_review_moderation_report(p_report_id bigint,p_status text,p_note text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null or not exists(select 1 from public.profiles where id=auth.uid() and role='admin' and coalesce(banned,false)=false) then raise exception 'ADMIN_REQUIRED'; end if;
  if p_status not in ('resolved','dismissed') or char_length(coalesce(p_note,''))>500 then return jsonb_build_object('success',false,'error','INVALID_REVIEW'); end if;
  update public.moderation_reports set status=p_status,admin_note=nullif(btrim(coalesce(p_note,'')),''),reviewed_by=auth.uid(),reviewed_at=now()
  where id=p_report_id and status='open';
  if not found then return jsonb_build_object('success',false,'error','REPORT_NOT_OPEN'); end if;
  return jsonb_build_object('success',true);
end $$;

revoke all on function public.create_chat_report(bigint,text,text) from public,anon;
grant execute on function public.create_chat_report(bigint,text,text) to authenticated;
revoke all on function public.create_pixel_report(bigint,integer,integer,text,text) from public,anon;
grant execute on function public.create_pixel_report(bigint,integer,integer,text,text) to authenticated;
revoke all on function public.admin_get_moderation_reports(text) from public,anon;
grant execute on function public.admin_get_moderation_reports(text) to authenticated;
revoke all on function public.admin_review_moderation_report(bigint,text,text) from public,anon;
grant execute on function public.admin_review_moderation_report(bigint,text,text) to authenticated;

commit;
