-- Administrator violation log.
-- Signals are for human review only: this migration never bans users automatically.

begin;

create table if not exists public.game_rule_violations (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.profiles(id) on delete cascade,
    related_user_id uuid references public.profiles(id) on delete set null,
    violation_type text not null check (
        violation_type in ('profanity', 'referral_multiaccount')
    ),
    evidence text not null,
    source_key text not null unique,
    risk_score integer not null default 0 check (
        risk_score between 0 and 100
    ),
    occurred_at timestamptz not null default clock_timestamp(),
    created_at timestamptz not null default clock_timestamp()
);

create index if not exists game_rule_violations_recent_idx
    on public.game_rule_violations (occurred_at desc, id desc);

create index if not exists game_rule_violations_user_idx
    on public.game_rule_violations (user_id, occurred_at desc);

alter table public.game_rule_violations enable row level security;

revoke all on table public.game_rule_violations
    from public, anon, authenticated;

create or replace function public.contains_chat_profanity(
    p_message text
)
returns boolean
language sql
immutable
set search_path = public
as $$
    select translate(lower(coalesce(p_message, '')), 'ё', 'е') ~
        '(^|[^а-яa-z])(бля(дь|ть)?|сука|сучка|хуй|хуя|хуе|хуи|пизд[а-я]*|еб[а-я]*|мудак|долбоеб|гандон|гондон|пидор[а-я]*|шлюха)([^а-яa-z]|$)';
$$;

revoke all on function public.contains_chat_profanity(text)
    from public, anon, authenticated;

create or replace function public.record_chat_profanity_violation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if new.message_type = 'user'
       and coalesce(new.is_admin_announcement, false) = false
       and not exists (
           select 1
           from public.profiles p
           where p.id = new.user_id
             and p.role = 'admin'
       )
       and public.contains_chat_profanity(new.message)
    then
        insert into public.game_rule_violations (
            user_id,
            violation_type,
            evidence,
            source_key,
            risk_score,
            occurred_at
        )
        values (
            new.user_id,
            'profanity',
            'Сообщение в чате: ' || left(new.message, 300),
            'chat:' || new.id::text,
            40,
            new.created_at
        )
        on conflict (source_key) do nothing;
    end if;

    return new;
end;
$$;

revoke all on function public.record_chat_profanity_violation()
    from public, anon, authenticated;

drop trigger if exists chat_messages_record_profanity
    on public.chat_messages;

create trigger chat_messages_record_profanity
after insert on public.chat_messages
for each row
execute function public.record_chat_profanity_violation();

insert into public.game_rule_violations (
    user_id,
    violation_type,
    evidence,
    source_key,
    risk_score,
    occurred_at
)
select
    cm.user_id,
    'profanity',
    'Сообщение в чате: ' || left(cm.message, 300),
    'chat:' || cm.id::text,
    40,
    cm.created_at
from public.chat_messages cm
join public.profiles p on p.id = cm.user_id
where cm.created_at >= clock_timestamp() - interval '90 days'
  and cm.message_type = 'user'
  and coalesce(cm.is_admin_announcement, false) = false
  and coalesce(p.role, 'student') <> 'admin'
  and public.contains_chat_profanity(cm.message)
on conflict (source_key) do nothing;

create or replace function public.admin_refresh_rule_violations()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
    v_risks jsonb;
    v_item jsonb;
    v_referral record;
    v_inserted integer := 0;
    v_score integer;
    v_reasons jsonb;
begin
    if auth.uid() is null or not exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.role = 'admin'
          and coalesce(p.banned, false) = false
    ) then
        raise exception 'ADMIN_REQUIRED';
    end if;

    v_risks := public.admin_get_multiaccount_risk();

    for v_item in
        select value
        from jsonb_array_elements(coalesce(v_risks, '[]'::jsonb))
    loop
        v_score := coalesce((v_item ->> 'risk_score')::integer, 0);
        v_reasons := coalesce(v_item -> 'reasons', '[]'::jsonb);

        if v_score < 30
           or not (v_reasons @> '["Аккаунты связаны рефералом"]'::jsonb)
        then
            continue;
        end if;

        select
            sr.invited_id,
            sr.inviter_id,
            sr.created_at
        into v_referral
        from public.student_referrals sr
        where (
            sr.invited_id = (v_item ->> 'user_a_id')::uuid
            and sr.inviter_id = (v_item ->> 'user_b_id')::uuid
        ) or (
            sr.invited_id = (v_item ->> 'user_b_id')::uuid
            and sr.inviter_id = (v_item ->> 'user_a_id')::uuid
        )
        limit 1;

        if found then
            insert into public.game_rule_violations (
                user_id,
                related_user_id,
                violation_type,
                evidence,
                source_key,
                risk_score,
                occurred_at
            )
            values (
                v_referral.invited_id,
                v_referral.inviter_id,
                'referral_multiaccount',
                format(
                    'Реферальная пара: %s ↔ %s. Риск %s/100. Признаки: %s',
                    coalesce(v_item ->> 'user_a_username', '—'),
                    coalesce(v_item ->> 'user_b_username', '—'),
                    v_score,
                    (
                        select string_agg(value, ', ')
                        from jsonb_array_elements_text(v_reasons)
                    )
                ),
                'referral:' || v_referral.invited_id::text,
                v_score,
                v_referral.created_at
            )
            on conflict (source_key) do update set
                evidence = excluded.evidence,
                risk_score = excluded.risk_score;

            if found then
                v_inserted := v_inserted + 1;
            end if;
        end if;
    end loop;

    return jsonb_build_object(
        'success', true,
        'signals_processed', v_inserted
    );
end;
$$;

create or replace function public.admin_get_rule_violations(
    p_type text default 'all'
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
    v_result jsonb;
begin
    if auth.uid() is null or not exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
          and p.role = 'admin'
          and coalesce(p.banned, false) = false
    ) then
        raise exception 'ADMIN_REQUIRED';
    end if;

    if coalesce(p_type, 'all') not in (
        'all',
        'profanity',
        'referral_multiaccount'
    ) then
        raise exception 'INVALID_VIOLATION_TYPE';
    end if;

    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'violation_id', v.id,
                'user_id', v.user_id,
                'username', p.username,
                'nickname', p.nickname,
                'class_name', c.name,
                'violation_type', v.violation_type,
                'evidence', v.evidence,
                'risk_score', v.risk_score,
                'occurred_at', v.occurred_at,
                'banned', coalesce(p.banned, false),
                'related_user_id', v.related_user_id,
                'related_username', rp.username
            )
            order by v.occurred_at desc, v.id desc
        ),
        '[]'::jsonb
    )
    into v_result
    from public.game_rule_violations v
    join public.profiles p on p.id = v.user_id
    left join public.classes c on c.id = p.class_id
    left join public.profiles rp on rp.id = v.related_user_id
    where p_type = 'all'
       or v.violation_type = p_type;

    return v_result;
end;
$$;

revoke all on function public.admin_refresh_rule_violations()
    from public, anon;
grant execute on function public.admin_refresh_rule_violations()
    to authenticated;

revoke all on function public.admin_get_rule_violations(text)
    from public, anon;
grant execute on function public.admin_get_rule_violations(text)
    to authenticated;

notify pgrst, 'reload schema';

commit;

select jsonb_build_object(
    'violation_table',
        to_regclass('public.game_rule_violations') is not null,
    'profanity_trigger',
        exists (
            select 1
            from pg_trigger
            where tgname = 'chat_messages_record_profanity'
              and not tgisinternal
        ),
    'admin_list_rpc',
        to_regprocedure(
            'public.admin_get_rule_violations(text)'
        ) is not null,
    'admin_refresh_rpc',
        to_regprocedure(
            'public.admin_refresh_rule_violations()'
        ) is not null,
    'automatic_bans', false
) as result;
