begin;

-- School Pixel Battle: одноразовые промокоды.
-- Первый тип награды: cooldown 1 секунда на 1 час.
-- Промокоды хранятся только как SHA-256-хэши.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.promo_codes (
    id bigint generated by default as identity primary key,
    code_hash text not null unique,
    code_hint text,
    title text not null default 'Пиксельный час',
    reward_type text not null default 'pixel_hour'
        check (reward_type in ('pixel_hour')),
    duration_seconds integer not null default 3600
        check (duration_seconds between 60 and 86400),
    cooldown_seconds integer not null default 1
        check (cooldown_seconds between 1 and 60),
    max_redemptions integer not null default 1
        check (max_redemptions >= 1),
    redemption_count integer not null default 0
        check (redemption_count >= 0),
    active boolean not null default true,
    expires_at timestamptz,
    created_at timestamptz not null default clock_timestamp()
);

create table if not exists public.promo_redemptions (
    id bigint generated by default as identity primary key,
    promo_code_id bigint not null
        references public.promo_codes(id) on delete restrict,
    user_id uuid not null
        references public.profiles(id) on delete cascade,
    redeemed_at timestamptz not null default clock_timestamp(),
    benefit_until timestamptz not null,
    unique (promo_code_id, user_id)
);

create index if not exists promo_redemptions_user_until_idx
    on public.promo_redemptions(user_id, benefit_until desc);

alter table public.promo_codes enable row level security;
alter table public.promo_redemptions enable row level security;

revoke all on table public.promo_codes from public, anon, authenticated;
revoke all on table public.promo_redemptions from public, anon, authenticated;
revoke all on sequence public.promo_codes_id_seq from public, anon, authenticated;
revoke all on sequence public.promo_redemptions_id_seq from public, anon, authenticated;

create or replace function public.get_my_promo_status()
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    v_user_id uuid := auth.uid();
    v_now timestamptz := clock_timestamp();
    v_until timestamptz;
    v_title text;
begin
    if v_user_id is null then
        raise exception 'NOT_AUTHENTICATED';
    end if;

    select r.benefit_until, c.title
    into v_until, v_title
    from public.promo_redemptions r
    join public.promo_codes c on c.id = r.promo_code_id
    where r.user_id = v_user_id
      and c.reward_type = 'pixel_hour'
      and r.benefit_until > v_now
    order by r.benefit_until desc
    limit 1;

    return jsonb_build_object(
        'active', v_until is not null,
        'title', v_title,
        'benefit_until', v_until,
        'remaining_seconds', case
            when v_until is null then 0
            else greatest(
                0,
                floor(extract(epoch from (v_until - v_now)))::integer
            )
        end,
        'cooldown', case when v_until is null then null else 1 end,
        'server_now', v_now
    );
end;
$$;

create or replace function public.redeem_promo_code(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    v_user_id uuid := auth.uid();
    v_now timestamptz := clock_timestamp();
    v_normalized_code text;
    v_code_hash text;
    v_code public.promo_codes%rowtype;
    v_benefit_until timestamptz;
begin
    if v_user_id is null then
        raise exception 'NOT_AUTHENTICATED';
    end if;

    perform 1
    from public.profiles
    where id = v_user_id
      and banned = false
    for update;

    if not found then
        raise exception 'PROFILE_NOT_FOUND_OR_BANNED';
    end if;

    v_normalized_code := upper(trim(coalesce(p_code, '')));

    if length(v_normalized_code) < 6
       or length(v_normalized_code) > 64 then
        return jsonb_build_object(
            'success', false,
            'reason', 'INVALID_CODE'
        );
    end if;

    v_code_hash := encode(
        extensions.digest(v_normalized_code, 'sha256'),
        'hex'
    );

    select *
    into v_code
    from public.promo_codes
    where code_hash = v_code_hash
    for update;

    if not found then
        return jsonb_build_object(
            'success', false,
            'reason', 'INVALID_CODE'
        );
    end if;

    if not v_code.active then
        return jsonb_build_object(
            'success', false,
            'reason', 'CODE_INACTIVE'
        );
    end if;

    if v_code.expires_at is not null
       and v_code.expires_at <= v_now then
        return jsonb_build_object(
            'success', false,
            'reason', 'CODE_EXPIRED'
        );
    end if;

    if v_code.redemption_count >= v_code.max_redemptions then
        return jsonb_build_object(
            'success', false,
            'reason', 'CODE_ALREADY_USED'
        );
    end if;

    if exists (
        select 1
        from public.promo_redemptions
        where user_id = v_user_id
          and benefit_until > v_now
    ) then
        return jsonb_build_object(
            'success', false,
            'reason', 'PROMO_ALREADY_ACTIVE'
        );
    end if;

    if exists (
        select 1
        from public.promo_redemptions
        where promo_code_id = v_code.id
          and user_id = v_user_id
    ) then
        return jsonb_build_object(
            'success', false,
            'reason', 'ALREADY_REDEEMED'
        );
    end if;

    v_benefit_until :=
        v_now + make_interval(secs => v_code.duration_seconds);

    insert into public.promo_redemptions (
        promo_code_id,
        user_id,
        redeemed_at,
        benefit_until
    )
    values (
        v_code.id,
        v_user_id,
        v_now,
        v_benefit_until
    );

    update public.promo_codes
    set redemption_count = redemption_count + 1
    where id = v_code.id;

    return jsonb_build_object(
        'success', true,
        'title', v_code.title,
        'benefit_until', v_benefit_until,
        'remaining_seconds', v_code.duration_seconds,
        'cooldown', v_code.cooldown_seconds,
        'server_now', v_now
    );
end;
$$;

-- Безопасно добавляем промокоды к уже существующей логике
-- Турбокисти, не переписывая place_pixel() целиком.
do $migration$
declare
    v_definition text;
    v_old text := $old$
    select boost_until
    into v_boost_until
    from public.daily_task_progress
    where user_id = v_user_id
      and boost_activated_at is not null
      and boost_until > v_now
    order by boost_until desc
    limit 1;
$old$;
    v_new text := $new$
    select max(active_until)
    into v_boost_until
    from (
        select boost_until as active_until
        from public.daily_task_progress
        where user_id = v_user_id
          and boost_activated_at is not null
          and boost_until > v_now

        union all

        select r.benefit_until as active_until
        from public.promo_redemptions r
        join public.promo_codes c on c.id = r.promo_code_id
        where r.user_id = v_user_id
          and c.reward_type = 'pixel_hour'
          and r.benefit_until > v_now
    ) active_pixel_boosts;
$new$;
    v_occurrences integer;
begin
    select pg_get_functiondef(
        'public.place_pixel(integer,integer,text)'::regprocedure
    )
    into v_definition;

    v_occurrences := (
        length(v_definition) - length(replace(v_definition, v_old, ''))
    ) / length(v_old);

    if v_occurrences <> 1 then
        raise exception
            'PLACE_PIXEL_DEFINITION_CHANGED: expected 1 boost query, found %',
            v_occurrences;
    end if;

    execute replace(v_definition, v_old, v_new);
end;
$migration$;

revoke all on function public.get_my_promo_status()
    from public, anon;
revoke all on function public.redeem_promo_code(text)
    from public, anon;

grant execute on function public.get_my_promo_status()
    to authenticated;
grant execute on function public.redeem_promo_code(text)
    to authenticated;

revoke all on function public.place_pixel(integer, integer, text)
    from public, anon;
grant execute on function public.place_pixel(integer, integer, text)
    to authenticated;

commit;

select jsonb_build_object(
    'promo_codes_table',
        to_regclass('public.promo_codes') is not null,
    'promo_redemptions_table',
        to_regclass('public.promo_redemptions') is not null,
    'redeem_rpc',
        to_regprocedure('public.redeem_promo_code(text)') is not null,
    'status_rpc',
        to_regprocedure('public.get_my_promo_status()') is not null,
    'place_pixel_reads_promos',
        position(
            'from public.promo_redemptions r'
            in pg_get_functiondef(
                'public.place_pixel(integer,integer,text)'::regprocedure
            )
        ) > 0
) as promo_codes_install_check;
