-- Server-side piCoin wallet, seven-day login rewards and Turbo Brush shop.
begin;
create table if not exists public.pi_coin_wallets(
 user_id uuid primary key references public.profiles(id) on delete cascade,
 balance integer not null default 0 check(balance>=0),
 streak_day integer not null default 0 check(streak_day between 0 and 7),
 last_claim_date date,updated_at timestamptz not null default clock_timestamp());
create table if not exists public.pi_coin_transactions(
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 amount integer not null check(amount<>0),
 reason text not null check(reason in('daily_bonus','turbo_purchase')),
 reference_date date,created_at timestamptz not null default clock_timestamp());
create unique index if not exists pi_coin_daily_once_idx on public.pi_coin_transactions(user_id,reference_date) where reason='daily_bonus';
create table if not exists public.pi_coin_boosts(
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 price integer not null check(price>0),purchased_at timestamptz not null default clock_timestamp(),active_until timestamptz not null);
create index if not exists pi_coin_boosts_user_until_idx on public.pi_coin_boosts(user_id,active_until desc);
alter table public.pi_coin_wallets enable row level security;
alter table public.pi_coin_transactions enable row level security;
alter table public.pi_coin_boosts enable row level security;
revoke all on table public.pi_coin_wallets,public.pi_coin_transactions,public.pi_coin_boosts from public,anon,authenticated;
revoke all on sequence public.pi_coin_transactions_id_seq,public.pi_coin_boosts_id_seq from public,anon,authenticated;

create or replace function public.get_pi_coin_status() returns jsonb language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid();n timestamptz:=clock_timestamp();d date:=(n at time zone 'Asia/Almaty')::date;w public.pi_coin_wallets%rowtype;cd integer;bu timestamptz;
begin
 if u is null then raise exception 'NOT_AUTHENTICATED';end if;
 perform 1 from public.profiles where id=u and banned=false;if not found then raise exception 'PROFILE_NOT_FOUND_OR_BANNED';end if;
 insert into public.pi_coin_wallets(user_id) values(u) on conflict(user_id) do nothing;
 select * into w from public.pi_coin_wallets where user_id=u;
 if w.last_claim_date=d then cd:=greatest(w.streak_day,1);elsif w.last_claim_date=d-1 then cd:=mod(w.streak_day,7)+1;else cd:=1;end if;
 select max(active_until) into bu from public.pi_coin_boosts where user_id=u and active_until>n;
 return jsonb_build_object('balance',w.balance,'claim_day',cd,'claimed_today',w.last_claim_date=d,'streak_day',w.streak_day,'boost_until',bu,'server_now',n);
end$$;

create or replace function public.claim_pi_coin_daily() returns jsonb language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid();n timestamptz:=clock_timestamp();d date:=(n at time zone 'Asia/Almaty')::date;w public.pi_coin_wallets%rowtype;cd integer;r integer;rs integer[]:=array[5,5,10,10,15,20,35];
begin
 if u is null then raise exception 'NOT_AUTHENTICATED';end if;
 perform 1 from public.profiles where id=u and banned=false for update;if not found then raise exception 'PROFILE_NOT_FOUND_OR_BANNED';end if;
 insert into public.pi_coin_wallets(user_id) values(u) on conflict(user_id) do nothing;
 select * into w from public.pi_coin_wallets where user_id=u for update;
 if w.last_claim_date=d then return jsonb_build_object('success',false,'error','ALREADY_CLAIMED','status',public.get_pi_coin_status());end if;
 if w.last_claim_date=d-1 then cd:=mod(w.streak_day,7)+1;else cd:=1;end if;r:=rs[cd];
 update public.pi_coin_wallets set balance=balance+r,streak_day=cd,last_claim_date=d,updated_at=n where user_id=u;
 insert into public.pi_coin_transactions(user_id,amount,reason,reference_date) values(u,r,'daily_bonus',d);
 return jsonb_build_object('success',true,'reward',r,'status',public.get_pi_coin_status());
end$$;

create or replace function public.buy_pi_coin_turbo() returns jsonb language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid();n timestamptz:=clock_timestamp();w public.pi_coin_wallets%rowtype;prev timestamptz;until_at timestamptz;price constant integer:=120;
begin
 if u is null then raise exception 'NOT_AUTHENTICATED';end if;
 perform 1 from public.profiles where id=u and banned=false for update;if not found then raise exception 'PROFILE_NOT_FOUND_OR_BANNED';end if;
 insert into public.pi_coin_wallets(user_id) values(u) on conflict(user_id) do nothing;
 select * into w from public.pi_coin_wallets where user_id=u for update;
 if w.balance<price then return jsonb_build_object('success',false,'error','NOT_ENOUGH_COINS','status',public.get_pi_coin_status());end if;
 select max(active_until) into prev from public.pi_coin_boosts where user_id=u and active_until>n;
 until_at:=greatest(coalesce(prev,n),n)+interval '10 minutes';
 update public.pi_coin_wallets set balance=balance-price,updated_at=n where user_id=u;
 insert into public.pi_coin_boosts(user_id,price,purchased_at,active_until) values(u,price,n,until_at);
 insert into public.pi_coin_transactions(user_id,amount,reason) values(u,-price,'turbo_purchase');
 return jsonb_build_object('success',true,'active_until',until_at,'status',public.get_pi_coin_status());
end$$;

do $m$ declare def text;needle text:=E'    ) active_pixel_boosts;';replacement text:=E'        union all\n\n        select b.active_until, 1 as active_cooldown\n        from public.pi_coin_boosts b\n        where b.user_id = v_user_id\n          and b.active_until > v_now\n    ) active_pixel_boosts;';hits integer;
begin
 select pg_get_functiondef('public.place_pixel(integer,integer,text)'::regprocedure) into def;
 if position('from public.pi_coin_boosts b' in def)=0 then
  hits:=(length(def)-length(replace(def,needle,'')))/length(needle);
  if hits<>1 then raise exception 'PLACE_PIXEL_BOOST_BLOCK_CHANGED: expected 1 block, found %',hits;end if;
  execute replace(def,needle,replacement);
 end if;
end$m$;
revoke all on function public.get_pi_coin_status(),public.claim_pi_coin_daily(),public.buy_pi_coin_turbo() from public,anon;
grant execute on function public.get_pi_coin_status(),public.claim_pi_coin_daily(),public.buy_pi_coin_turbo() to authenticated;
commit;
select jsonb_build_object('wallets',to_regclass('public.pi_coin_wallets') is not null,'transactions',to_regclass('public.pi_coin_transactions') is not null,'boosts',to_regclass('public.pi_coin_boosts') is not null,'place_pixel_support',position('from public.pi_coin_boosts b' in pg_get_functiondef('public.place_pixel(integer,integer,text)'::regprocedure))>0) as pi_coin_install_check;
