-- Purchasable map items: anonymous bomb, public beacon and private pixel detector.
begin;
alter table public.pixels alter column class_id drop not null;
alter table public.pi_coin_transactions drop constraint if exists pi_coin_transactions_reason_check;
alter table public.pi_coin_transactions add column if not exists item_type text;
alter table public.pi_coin_transactions add constraint pi_coin_transactions_reason_check check(reason in('daily_bonus','turbo_purchase','item_purchase'));
create table if not exists public.map_item_inventory(user_id uuid not null references public.profiles(id) on delete cascade,item_type text not null check(item_type in('bomb','beacon','detector')),quantity integer not null default 0 check(quantity between 0 and 100),updated_at timestamptz not null default clock_timestamp(),primary key(user_id,item_type));
create table if not exists public.map_item_ledger(id bigint generated by default as identity primary key,user_id uuid not null references public.profiles(id) on delete cascade,item_type text not null check(item_type in('bomb','beacon','detector')),action text not null check(action in('purchase','use')),quantity integer not null check(quantity in(-1,1)),season_id bigint references public.seasons(id) on delete set null,x integer,y integer,created_at timestamptz not null default clock_timestamp());
create index if not exists map_item_ledger_user_day_idx on public.map_item_ledger(user_id,item_type,created_at desc);
create table if not exists public.map_bomb_events(id bigint generated by default as identity primary key,season_id bigint not null references public.seasons(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete restrict,center_x integer not null,center_y integer not null,created_at timestamptz not null default clock_timestamp());
create table if not exists public.map_bomb_cells(bomb_id bigint not null references public.map_bomb_events(id) on delete cascade,x integer not null,y integer not null,color text not null,primary key(bomb_id,x,y));
create index if not exists map_bomb_cells_lookup_idx on public.map_bomb_cells(x,y,bomb_id);
create table if not exists public.map_beacons(id bigint generated by default as identity primary key,season_id bigint not null references public.seasons(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,class_id bigint references public.classes(id) on delete set null,x integer not null,y integer not null,label text not null check(char_length(label) between 1 and 32),created_at timestamptz not null default clock_timestamp(),expires_at timestamptz not null,unique(season_id,x,y));
create table if not exists public.map_pixel_reveals(id bigint generated by default as identity primary key,user_id uuid not null references public.profiles(id) on delete cascade,season_id bigint not null references public.seasons(id) on delete cascade,x integer not null,y integer not null,pixel_updated_at timestamptz not null,revealed_user_id uuid not null references public.profiles(id) on delete cascade,created_at timestamptz not null default clock_timestamp(),unique(user_id,season_id,x,y,pixel_updated_at));
alter table public.map_item_inventory enable row level security;alter table public.map_item_ledger enable row level security;alter table public.map_bomb_events enable row level security;alter table public.map_bomb_cells enable row level security;alter table public.map_beacons enable row level security;alter table public.map_pixel_reveals enable row level security;
revoke all on table public.map_item_inventory,public.map_item_ledger,public.map_bomb_events,public.map_bomb_cells,public.map_beacons,public.map_pixel_reveals from public,anon,authenticated;
revoke all on sequence public.map_item_ledger_id_seq,public.map_bomb_events_id_seq,public.map_beacons_id_seq,public.map_pixel_reveals_id_seq from public,anon,authenticated;

create or replace function public.get_map_item_status(p_season_id bigint default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid();bal integer:=0;inv jsonb;bs jsonb:='[]'::jsonb;cs jsonb:='[]'::jsonb;
begin
 if u is null then raise exception 'NOT_AUTHENTICATED';end if;select balance into bal from public.pi_coin_wallets where user_id=u;
 select jsonb_build_object('bomb',coalesce(max(quantity) filter(where item_type='bomb'),0),'beacon',coalesce(max(quantity) filter(where item_type='beacon'),0),'detector',coalesce(max(quantity) filter(where item_type='detector'),0)) into inv from public.map_item_inventory where user_id=u;
 if p_season_id is not null then
  select coalesce(jsonb_agg(jsonb_build_object('id',b.id,'x',b.x,'y',b.y,'label',b.label,'class_name',c.name,'expires_at',b.expires_at) order by b.created_at),'[]'::jsonb) into bs from public.map_beacons b left join public.classes c on c.id=b.class_id where b.season_id=p_season_id and b.expires_at>clock_timestamp();
  select coalesce(jsonb_agg(jsonb_build_object('x',bc.x,'y',bc.y)),'[]'::jsonb) into cs from public.map_bomb_cells bc join public.map_bomb_events e on e.id=bc.bomb_id join public.pixels p on p.season_id=e.season_id and p.x=bc.x and p.y=bc.y and p.user_id=e.user_id and p.updated_at=e.created_at where e.season_id=p_season_id;
 end if;return jsonb_build_object('balance',coalesce(bal,0),'inventory',inv,'beacons',bs,'bomb_cells',cs);
end$$;
create or replace function public.buy_map_item(p_item_type text) returns jsonb language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid();n timestamptz:=clock_timestamp();d date:=(n at time zone 'Asia/Almaty')::date;price integer;daily_cap integer;stock_cap integer;buys integer;qty integer;w public.pi_coin_wallets%rowtype;
begin
 if p_item_type='bomb' then price:=450;daily_cap:=1;stock_cap:=3;elsif p_item_type='beacon' then price:=90;daily_cap:=2;stock_cap:=5;elsif p_item_type='detector' then price:=15;daily_cap:=10;stock_cap:=20;else return jsonb_build_object('success',false,'error','INVALID_ITEM');end if;
 perform 1 from public.profiles where id=u and banned=false for update;if not found then raise exception 'PROFILE_NOT_FOUND_OR_BANNED';end if;
 insert into public.pi_coin_wallets(user_id) values(u) on conflict(user_id) do nothing;select * into w from public.pi_coin_wallets where user_id=u for update;
 select count(*) into buys from public.map_item_ledger where user_id=u and item_type=p_item_type and action='purchase' and (created_at at time zone 'Asia/Almaty')::date=d;if buys>=daily_cap then return jsonb_build_object('success',false,'error','DAILY_LIMIT');end if;
 insert into public.map_item_inventory(user_id,item_type) values(u,p_item_type) on conflict(user_id,item_type) do nothing;select quantity into qty from public.map_item_inventory where user_id=u and item_type=p_item_type for update;
 if qty>=stock_cap then return jsonb_build_object('success',false,'error','INVENTORY_LIMIT');end if;if w.balance<price then return jsonb_build_object('success',false,'error','NOT_ENOUGH_COINS');end if;
 update public.pi_coin_wallets set balance=balance-price,updated_at=n where user_id=u;update public.map_item_inventory set quantity=quantity+1,updated_at=n where user_id=u and item_type=p_item_type;
 insert into public.map_item_ledger(user_id,item_type,action,quantity,created_at) values(u,p_item_type,'purchase',1,n);insert into public.pi_coin_transactions(user_id,amount,reason,item_type) values(u,-price,'item_purchase',p_item_type);
 return jsonb_build_object('success',true,'status',public.get_map_item_status(null));
end$$;
create or replace function public.use_map_bomb(p_x integer,p_y integer) returns jsonb language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid();n timestamptz:=clock_timestamp();s public.seasons%rowtype;qty integer;used integer;bid bigint;cells jsonb;
begin
 perform 1 from public.profiles where id=u and banned=false for update;if not found then raise exception 'PROFILE_NOT_FOUND_OR_BANNED';end if;select * into s from public.seasons where is_active=true and starts_at<=n and ends_at>n order by starts_at desc limit 1;if not found then raise exception 'NO_ACTIVE_SEASON';end if;
 if p_x<4 or p_y<4 or p_x>=s.map_width-4 or p_y>=s.map_height-4 then return jsonb_build_object('success',false,'error','EDGE_LIMIT');end if;
 select quantity into qty from public.map_item_inventory where user_id=u and item_type='bomb' for update;if coalesce(qty,0)<1 then return jsonb_build_object('success',false,'error','NO_ITEM');end if;
 select count(*) into used from public.map_bomb_events where user_id=u and season_id=s.id;if used>=2 then return jsonb_build_object('success',false,'error','SEASON_LIMIT');end if;
 insert into public.map_bomb_events(season_id,user_id,center_x,center_y,created_at) values(s.id,u,p_x,p_y,n) returning id into bid;
 with offsets as(select dx,dy,abs(dx)+abs(dy) dist from generate_series(-4,4) dx cross join generate_series(-4,4) dy where abs(dx)+abs(dy)<=4),recorded as(insert into public.map_bomb_cells(bomb_id,x,y,color) select bid,p_x+dx,p_y+dy,case when dist=4 then '#475569' when dist=3 then '#334155' else '#111111' end from offsets returning x,y,color)
 insert into public.pixels(season_id,x,y,color,user_id,class_id,updated_at) select s.id,x,y,color,u,null,n from recorded on conflict(season_id,x,y) do update set color=excluded.color,user_id=excluded.user_id,class_id=null,updated_at=excluded.updated_at;
 update public.map_item_inventory set quantity=quantity-1,updated_at=n where user_id=u and item_type='bomb';insert into public.map_item_ledger(user_id,item_type,action,quantity,season_id,x,y,created_at) values(u,'bomb','use',-1,s.id,p_x,p_y,n);
 select jsonb_agg(jsonb_build_object('x',x,'y',y,'color',color)) into cells from public.map_bomb_cells where bomb_id=bid;return jsonb_build_object('success',true,'cells',cells,'status',public.get_map_item_status(s.id));
end$$;
create or replace function public.place_map_beacon(p_x integer,p_y integer,p_label text) returns jsonb language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid();n timestamptz:=clock_timestamp();s public.seasons%rowtype;pr public.profiles%rowtype;qty integer;v_label text:=btrim(coalesce(p_label,''));cnt integer;
begin
 select * into pr from public.profiles where id=u and banned=false for update;if not found then raise exception 'PROFILE_NOT_FOUND_OR_BANNED';end if;select * into s from public.seasons where is_active=true and starts_at<=n and ends_at>n order by starts_at desc limit 1;if not found then raise exception 'NO_ACTIVE_SEASON';end if;
 if p_x<0 or p_y<0 or p_x>=s.map_width or p_y>=s.map_height then raise exception 'INVALID_COORDINATES';end if;if char_length(v_label)<1 or char_length(v_label)>32 then return jsonb_build_object('success',false,'error','INVALID_LABEL');end if;if v_label~*'(https?://|www\.|t\.me/)' then return jsonb_build_object('success',false,'error','NO_LINKS');end if;if public.contains_chat_profanity(v_label) then return jsonb_build_object('success',false,'error','PROFANITY');end if;
 select quantity into qty from public.map_item_inventory where user_id=u and item_type='beacon' for update;if coalesce(qty,0)<1 then return jsonb_build_object('success',false,'error','NO_ITEM');end if;
 select count(*) into cnt from public.map_beacons where user_id=u and season_id=s.id and expires_at>n;if cnt>=3 then return jsonb_build_object('success',false,'error','BEACON_LIMIT');end if;select count(*) into cnt from public.map_beacons where class_id=pr.class_id and season_id=s.id and expires_at>n;if cnt>=10 then return jsonb_build_object('success',false,'error','BEACON_LIMIT');end if;
 if exists(select 1 from public.map_beacons where season_id=s.id and x=p_x and y=p_y) then return jsonb_build_object('success',false,'error','CELL_OCCUPIED');end if;
 insert into public.map_beacons(season_id,user_id,class_id,x,y,label,created_at,expires_at) values(s.id,u,pr.class_id,p_x,p_y,v_label,n,s.ends_at);update public.map_item_inventory set quantity=quantity-1,updated_at=n where user_id=u and item_type='beacon';insert into public.map_item_ledger(user_id,item_type,action,quantity,season_id,x,y,created_at) values(u,'beacon','use',-1,s.id,p_x,p_y,n);
 return jsonb_build_object('success',true,'status',public.get_map_item_status(s.id));
end$$;
create or replace function public.reveal_pixel_owner(p_x integer,p_y integer) returns jsonb language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid();n timestamptz:=clock_timestamp();s public.seasons%rowtype;px public.pixels%rowtype;qty integer;owner_rec record;cached_id bigint;
begin
 perform 1 from public.profiles where id=u and banned=false;if not found then raise exception 'PROFILE_NOT_FOUND_OR_BANNED';end if;select * into s from public.seasons where is_active=true and starts_at<=n and ends_at>n order by starts_at desc limit 1;if not found then raise exception 'NO_ACTIVE_SEASON';end if;
 select * into px from public.pixels where season_id=s.id and x=p_x and y=p_y;if not found then return jsonb_build_object('success',false,'error','EMPTY_PIXEL');end if;if px.user_id=u then return jsonb_build_object('success',false,'error','OWN_PIXEL');end if;
 if exists(select 1 from public.map_bomb_cells bc join public.map_bomb_events e on e.id=bc.bomb_id where e.season_id=s.id and bc.x=p_x and bc.y=p_y and e.user_id=px.user_id and e.created_at=px.updated_at) then return jsonb_build_object('success',false,'error','ANONYMOUS_BOMB');end if;
 select p.nickname,c.name class_name into owner_rec from public.profiles p left join public.classes c on c.id=p.class_id where p.id=px.user_id;select r.id into cached_id from public.map_pixel_reveals r where r.user_id=u and r.season_id=s.id and r.x=p_x and r.y=p_y and r.pixel_updated_at=px.updated_at limit 1;
 if found then return jsonb_build_object('success',true,'nickname',owner_rec.nickname,'class_name',owner_rec.class_name,'cached',true,'status',public.get_map_item_status(s.id));end if;
 select quantity into qty from public.map_item_inventory where user_id=u and item_type='detector' for update;if coalesce(qty,0)<1 then return jsonb_build_object('success',false,'error','NO_ITEM');end if;
 update public.map_item_inventory set quantity=quantity-1,updated_at=n where user_id=u and item_type='detector';insert into public.map_pixel_reveals(user_id,season_id,x,y,pixel_updated_at,revealed_user_id,created_at) values(u,s.id,p_x,p_y,px.updated_at,px.user_id,n);insert into public.map_item_ledger(user_id,item_type,action,quantity,season_id,x,y,created_at) values(u,'detector','use',-1,s.id,p_x,p_y,n);
 return jsonb_build_object('success',true,'nickname',owner_rec.nickname,'class_name',owner_rec.class_name,'cached',false,'status',public.get_map_item_status(s.id));
end$$;
create or replace function public.buy_pi_coin_turbo() returns jsonb language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid();n timestamptz:=clock_timestamp();w public.pi_coin_wallets%rowtype;prev timestamptz;until_at timestamptz;price constant integer:=160;
begin
 if u is null then raise exception 'NOT_AUTHENTICATED';end if;perform 1 from public.profiles where id=u and banned=false for update;if not found then raise exception 'PROFILE_NOT_FOUND_OR_BANNED';end if;insert into public.pi_coin_wallets(user_id) values(u) on conflict(user_id) do nothing;select * into w from public.pi_coin_wallets where user_id=u for update;
 if w.balance<price then return jsonb_build_object('success',false,'error','NOT_ENOUGH_COINS','status',public.get_pi_coin_status());end if;select max(active_until) into prev from public.pi_coin_boosts where user_id=u and active_until>n;until_at:=greatest(coalesce(prev,n),n)+interval '10 minutes';update public.pi_coin_wallets set balance=balance-price,updated_at=n where user_id=u;insert into public.pi_coin_boosts(user_id,price,purchased_at,active_until) values(u,price,n,until_at);insert into public.pi_coin_transactions(user_id,amount,reason) values(u,-price,'turbo_purchase');return jsonb_build_object('success',true,'active_until',until_at,'status',public.get_pi_coin_status());
end$$;
revoke all on function public.get_map_item_status(bigint),public.buy_map_item(text),public.use_map_bomb(integer,integer),public.place_map_beacon(integer,integer,text),public.reveal_pixel_owner(integer,integer) from public,anon;
grant execute on function public.get_map_item_status(bigint),public.buy_map_item(text),public.use_map_bomb(integer,integer),public.place_map_beacon(integer,integer,text),public.reveal_pixel_owner(integer,integer) to authenticated;
notify pgrst,'reload schema';commit;
select jsonb_build_object('inventory',to_regclass('public.map_item_inventory') is not null,'bombs',to_regclass('public.map_bomb_events') is not null,'beacons',to_regclass('public.map_beacons') is not null,'detectors',to_regclass('public.map_pixel_reveals') is not null) as map_items_install_check;
